[
{
"id" : 0,
"img" : "img/item/0.jpg",
"img1" : "img/item/1.jpg",
"img2" : "img/item/2.jpg",
"img3" : "img/item/3.jpg",
"img4" : "img/item/4.jpg",
"name" : "MIT LADY CHIC後露背傘擺上衣(黑)",
"price" : 80,
"description" : "飄逸的度假風氣息上衣，後露背的設計讓女孩散發輕盈的夏日小性感唷！",
"material" : "聚酯纖維 62% 嫘縈纖維 33% 彈性纖維 5%",
"madeIn" : "台灣",
"category" : "top",
"new" : "yes"
},
{
"id" : 1,
"img" : "img/item/1.jpg",
"img1" : "img/item/0.jpg",
"img2" : "img/item/2.jpg",
"img3" : "img/item/3.jpg",
"img4" : "img/item/4.jpg",
"name" : "MIT LADY CHIC後露背傘擺上衣(白)",
"price" : 80,
"description" : "飄逸的度假風氣息上衣，後露背的設計讓女孩散發輕盈的夏日小性感唷！",
"material" : "聚酯纖維 62% 嫘縈纖維 33% 彈性纖維 5%",
"madeIn" : "台灣",
"category" : "bottom",
"new" : "yes"
},
{
"id" : 2,
"img" : "img/item/2.jpg",
"img1" : "img/item/1.jpg",
"img2" : "img/item/0.jpg",
"img3" : "img/item/3.jpg",
"img4" : "img/item/4.jpg",
"name" : "MIT 舒適感柔棉圓領傘擺背心",
"price" : 80,
"description" : "MIT炎炎夏日穿著舒適感的柔棉商品為最佳選擇！領口圓領下擺傘狀設計，讓女孩們穿著時更顯知性小女孩的LOOK！",
"material" : "粘膠纖維 58.4% 棉 41.6%",
"madeIn" : "台灣",
"category" : "acc",
"new" : "yes"
},
{
"id" : 3,
"img" : "img/item/3.jpg",
"img1" : "img/item/1.jpg",
"img2" : "img/item/2.jpg",
"img3" : "img/item/0.jpg",
"img4" : "img/item/4.jpg",
"name" : "率性街頭割破不修邊背心(黑)",
"price" : 80,
"description" : "在簡單英文字背心上做上了割破設計，在隨性搭配牛仔褲OR寬褲就可以帥帥Der~",
"material" : "棉 100%",
"madeIn" : "台灣",
"category" : "shoes",
"new" : "yes"
},
{
"id" : 4,
"img" : "img/item/4.jpg",
"img1" : "img/item/1.jpg",
"img2" : "img/item/2.jpg",
"img3" : "img/item/3.jpg",
"img4" : "img/item/0.jpg",
"name" : "率性街頭割破不修邊背心(白)",
"price" : 80,
"description" : "在簡單英文字背心上做上了割破設計，在隨性搭配牛仔褲OR寬褲就可以帥帥Der~",
"material" : "棉 100%",
"madeIn" : "台灣",
"category" : "handmade",
"new" : "no"
}
]